server:
  port: 8082

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/spring
