server:
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always

jwt:
  persistence:
    password: password
    salt: 626F6F746966756C
  key:
    id: some_key_id
  expiration-time: 24 # hours

logging:
  level:
    org.springframework.security: TRACE